#!/bin/bash

#shell script to install git on Linux Windows MAC OS
#shell script is running

echo "shell script to install git"
echo "shell script running"

if [ "$(uname)"  ==  "Linux" ];
then
        echo "this is linux system, installing git"
        apt install git -y
elif [ "$(uname)"  ==  "Darwin" ];
then
        echo "thgis is not linux system, this is MAC OS"
        echo "installing git on MAC"
        brew install git
else echo "Not installing"
fi
