#!/bin/bash

#shell script to install git on Linux Windows MAC OS
#shell script is running

echo "shell script to install git"
echo "shell script running"

if [ "$(uname)"  ==  "Linux" ]; then
        echo "this is linux system, installing git"
	echo "installing git on Linux OS"
        sudo apt update && sudo apt install git -y

elif [ "$(uname)"  ==  "Darwin" ]; then
        echo "this is MAC OS, installing git "
        echo "installing git on MAC"
        brew install git

elif [[ "$(uname -o)" == "Cygwin"  || "$(uname -o)" == "Msys" ]]; then
	echo "this is windows OS, installing git"
	echo "installing git on windows"
	sudo apt update && sudo apt install git -y

else echo "Not supported OS , Not installing"

fi
